lesson_1
NadezhdaPenkrat/Java_FreeIT pull request #1
Opened 2021-02-17 21:13 UTC by NadezhdaPenkrat

Hi! Check, please

2021-02-18 19:45 UTC, IrenaKozlovskaya commented on lesson_1/hello/src/IsAllDifferentNum.java
> +            result = (number != 0) ? "contains the same number.." : "does not contain the same number.";
Нету сравнения цифр друг с другом?) не понимаю что такое result и зачем он здесь нужен

2021-02-20 15:28 UTC, RomanKashenok requested changes

2021-02-20 15:28 UTC, RomanKashenok commented on lesson_1/Hello.java
> +public class Hello {
Зачем 2 одинаковык классов

2021-02-20 15:28 UTC, RomanKashenok commented on lesson_1/hello/src/HelloNadezhda.java
> +        System.out.println ("Hello, Nadezhda");
Вообще я думал, что ты "Nadezhda" передашь в args

2021-02-20 15:28 UTC, RomanKashenok commented on lesson_1/hello/src/IsAllDifferentNum.java
> +            result = (number != 0) ? "contains the same number.." : "does not contain the same number.";
Да. Тут надо бы вычленить все 4 цифры и сравнить их между собой

2021-02-20 15:28 UTC, RomanKashenok commented on lesson_1/hello/src/ReverseOrderNumber.java
> +            System.out.print(number%10);
Ну ты просто распечатала его, но, думаю, составить из этого итоговое "перевернутое" число труда не составит :)

2021-02-20 15:28 UTC, RomanKashenok commented on lesson_1/hello/src/TimePrinter.java
> +        int d = (h - day) / 24; //С) дней + часов + минут + секунд.
попробуй число по больше (я взял 280501) 
77 часов 55 минут 1секунд
3 дней 77 часов 55 минут 1секунд
т.е. что-то не посчиталось правильно )))

2021-02-27 09:19 UTC, TheFallen058 approved these changes
please fix variable names

2021-02-27 09:19 UTC, TheFallen058 commented on lesson_1/com/freeit/src/Task5IsAllDifferentNum.java
> +        int a = number / 1000 % 10;
bad variable names

2021-02-27 09:19 UTC, TheFallen058 commented on lesson_1/com/freeit/src/Task5IsAllDifferentNum.java
> +            result = ( a != b && a != c && a != d && b != c && b != d && c != d ) ?
big condition - hard to read
next time try to simplify or implement other solution

2021-03-04 13:54 UTC, merged